#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# basics for drupal
cookbook 'apache2'
cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'php'
cookbook 'varnish'
cookbook 'hosts'
cookbook 'phpmyadmin'   # from user priestjim on github

cookbook 'openvpnc',
        :git=> 'git@github.com:rivimey/openvpnc.git'

# elife drupal module git repos, and highwire drupal base site
cookbook 'drupal-site-jnl-elife-cookbook',
        :git=> 'git@github.com:elifesciences/drupal-site-jnl-elife-cookbook.git'

# elife modified cookbooks for drupal installation
cookbook 'elife-drupal-cookbook',
        :git=> 'git@github.com:elifesciences/elife-drupal-cookbook.git'

cookbook 'elife-drush-cookbook',
        :git=> 'git@github.com:elifesciences/elife-drush-cookbook.git'

# - hosts
# - phpmyadmin

# TDODOs
# - provide specific versions for community cookbooks
