#!/bin/bash

cmd="$1"

case $cmd in

	"boxes")
		vagrant box add pre64-elife-rb1.9-chef-11 http://cdn.elifesciences.org/vm/pre64-elife-rb1.9-chef-11.box
		vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
		;;

	"preinstall")
		( \
		cd .. ;\
		git clone git@github.com:elifesciences/drupal-highwire.git ;\
		git clone git@github.com:elifesciences/drupal-site-jnl-elife.git ;\
		) ;\
		;;

	"update")
		librarian-chef update
		;;

	"up")
		shift
		# can do jnl up --provider=aws for example...
		vagrant up "$*"
		;;

	"provision")
		shift
		vagrant provision "$*"
		;;

	"clean")
		echo Cleaning: destroy default VM...
		vagrant destroy
		echo Cleaning: Delete temp files
		rm -rf Cheffile.lock cookbooks tmp roles
		mkdir -p roles
		echo Cleaned.
		;;

esac
